production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
  CLOUDINARY_URL: "cloudinary://542772996589441:2xKNbr9_IHRRP6_CPJ0TN6AUPos@dgffnsbui"
  GMAIL_ADDRESS: "robtuinte15@gmail.com"
  GMAIL_APP_PASSWORD: "pykfonaggvolmxyt"
