meta_product_name: "CFOhulp"
meta_title: "CFOhulp - CFO services"
meta_description: "Financiële services voor bedrijven en investeerders"
meta_image: "https://res.cloudinary.com/dgffnsbui/image/upload/v1591370842/banner-investeerder.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
